version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dms-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: dms_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: dms-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/dms_db
    ports:
      - "8000:8000"
    volumes:
      - ./input:/app/input
      - ./output:/app/output

volumes:
  postgres_data:
